/**
 * MK8DX track registry — all 96 tracks (48 base + 48 Booster Course Pass)
 * derived from `src/data/mk8dx-data.json`. IDs are cup-prefixed slugs to
 * disambiguate names that recur across cups (Mario Circuit appears in
 * Flower / Shell / Boomerang; Rainbow Road appears in 5 cups).
 *
 * If you ever need to regenerate this list from the source JSON, the
 * generation script is captured in
 * `docs/gs-pro-v1-track-item-content-inventory.md` §1.
 */

import type { Track } from "../types";

export const MK8DX_TRACKS: Track[] = [
  { id: "mushroom-mario-kart-stadium", name: "Mario Kart Stadium", cup: "Mushroom", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/mushroom/mario-kart-stadium.webp", game: "mk8dx" },
  { id: "mushroom-water-park", name: "Water Park", cup: "Mushroom", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/mushroom/water-park.webp", game: "mk8dx" },
  { id: "mushroom-sweet-sweet-canyon", name: "Sweet Sweet Canyon", cup: "Mushroom", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/mushroom/sweet-sweet-canyon.webp", game: "mk8dx" },
  { id: "mushroom-thwomp-ruins", name: "Thwomp Ruins", cup: "Mushroom", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/mushroom/thwomp-ruins.webp", game: "mk8dx" },
  { id: "flower-mario-circuit", name: "Mario Circuit", cup: "Flower", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/flower/mario-circuit.webp", game: "mk8dx" },
  { id: "flower-toad-harbor", name: "Toad Harbor", cup: "Flower", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/flower/toad-harbor.webp", game: "mk8dx" },
  { id: "flower-twisted-mansion", name: "Twisted Mansion", cup: "Flower", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/flower/twisted-mansion.webp", game: "mk8dx" },
  { id: "flower-shy-guy-falls", name: "Shy Guy Falls", cup: "Flower", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/flower/shy-guy-falls.webp", game: "mk8dx" },
  { id: "star-sunshine-airport", name: "Sunshine Airport", cup: "Star", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/star/sunshine-airport.webp", game: "mk8dx" },
  { id: "star-dolphin-shoals", name: "Dolphin Shoals", cup: "Star", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/star/dolphin-shoals.webp", game: "mk8dx" },
  { id: "star-electrodome", name: "Electrodome", cup: "Star", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/star/electrodome.webp", game: "mk8dx" },
  { id: "star-mount-wario", name: "Mount Wario", cup: "Star", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/star/mount-wario.webp", game: "mk8dx" },
  { id: "special-cloudtop-cruise", name: "Cloudtop Cruise", cup: "Special", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/special/cloudtop-cruise.webp", game: "mk8dx" },
  { id: "special-bone-dry-dunes", name: "Bone-Dry Dunes", cup: "Special", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/special/bone-dry-dunes.webp", game: "mk8dx" },
  { id: "special-bowsers-castle", name: "Bowser's Castle", cup: "Special", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/special/bowsers-castle.webp", game: "mk8dx" },
  { id: "special-rainbow-road", name: "Rainbow Road", cup: "Special", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/special/rainbow-road.webp", game: "mk8dx" },
  { id: "shell-moo-moo-meadows", name: "Moo Moo Meadows", cup: "Shell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/shell/moo-moo-meadows.webp", game: "mk8dx" },
  { id: "shell-mario-circuit", name: "Mario Circuit", cup: "Shell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/shell/mario-circuit.webp", game: "mk8dx" },
  { id: "shell-cheep-cheep-beach", name: "Cheep Cheep Beach", cup: "Shell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/shell/cheep-cheep-beach.webp", game: "mk8dx" },
  { id: "shell-toads-turnpike", name: "Toad's Turnpike", cup: "Shell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/shell/toads-turnpike.webp", game: "mk8dx" },
  { id: "banana-dry-dry-desert", name: "Dry Dry Desert", cup: "Banana", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/banana/dry-dry-desert.webp", game: "mk8dx" },
  { id: "banana-donut-plains-3", name: "Donut Plains 3", cup: "Banana", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/banana/donut-plains-3.webp", game: "mk8dx" },
  { id: "banana-royal-raceway", name: "Royal Raceway", cup: "Banana", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/banana/royal-raceway.webp", game: "mk8dx" },
  { id: "banana-dk-jungle", name: "DK Jungle", cup: "Banana", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/banana/dk-jungle.webp", game: "mk8dx" },
  { id: "leaf-wario-stadium", name: "Wario Stadium", cup: "Leaf", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/leaf/wario-stadium.webp", game: "mk8dx" },
  { id: "leaf-sherbet-land", name: "Sherbet Land", cup: "Leaf", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/leaf/sherbet-land.webp", game: "mk8dx" },
  { id: "leaf-music-park", name: "Music Park", cup: "Leaf", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/leaf/music-park.webp", game: "mk8dx" },
  { id: "leaf-yoshi-valley", name: "Yoshi Valley", cup: "Leaf", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/leaf/yoshi-valley.webp", game: "mk8dx" },
  { id: "lightning-tick-tock-clock", name: "Tick-Tock Clock", cup: "Lightning", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lightning/tick-tock-clock.webp", game: "mk8dx" },
  { id: "lightning-piranha-plant-slide", name: "Piranha Plant Slide", cup: "Lightning", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lightning/piranha-plant-slide.webp", game: "mk8dx" },
  { id: "lightning-grumble-volcano", name: "Grumble Volcano", cup: "Lightning", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lightning/grumble-volcano.webp", game: "mk8dx" },
  { id: "lightning-rainbow-road", name: "Rainbow Road", cup: "Lightning", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lightning/rainbow-road.webp", game: "mk8dx" },
  { id: "egg-yoshi-circuit", name: "Yoshi Circuit", cup: "Egg", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/egg/yoshi-circuit.webp", game: "mk8dx" },
  { id: "egg-excitebike-arena", name: "Excitebike Arena", cup: "Egg", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/egg/excitebike-arena.webp", game: "mk8dx" },
  { id: "egg-dragon-driftway", name: "Dragon Driftway", cup: "Egg", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/egg/dragon-driftway.webp", game: "mk8dx" },
  { id: "egg-mute-city", name: "Mute City", cup: "Egg", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/egg/mute-city.webp", game: "mk8dx" },
  { id: "triforce-warios-gold-mine", name: "Wario's Gold Mine", cup: "Triforce", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/triforce/warios-gold-mine.webp", game: "mk8dx" },
  { id: "triforce-rainbow-road", name: "Rainbow Road", cup: "Triforce", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/triforce/rainbow-road.webp", game: "mk8dx" },
  { id: "triforce-ice-ice-outpost", name: "Ice Ice Outpost", cup: "Triforce", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/triforce/ice-ice-outpost.webp", game: "mk8dx" },
  { id: "triforce-hyrule-circuit", name: "Hyrule Circuit", cup: "Triforce", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/triforce/hyrule-circuit.webp", game: "mk8dx" },
  { id: "crossing-baby-park", name: "Baby Park", cup: "Crossing", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/crossing/baby-park.webp", game: "mk8dx" },
  { id: "crossing-cheese-land", name: "Cheese Land", cup: "Crossing", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/crossing/cheese-land.webp", game: "mk8dx" },
  { id: "crossing-wild-woods", name: "Wild Woods", cup: "Crossing", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/crossing/wild-woods.webp", game: "mk8dx" },
  { id: "crossing-animal-crossing", name: "Animal Crossing", cup: "Crossing", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/crossing/animal-crossing.webp", game: "mk8dx" },
  { id: "bell-neo-bowser-city", name: "Neo Bowser City", cup: "Bell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/bell/neo-bowser-city.webp", game: "mk8dx" },
  { id: "bell-ribbon-road", name: "Ribbon Road", cup: "Bell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/bell/ribbon-road.webp", game: "mk8dx" },
  { id: "bell-super-bell-subway", name: "Super Bell Subway", cup: "Bell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/bell/super-bell-subway.webp", game: "mk8dx" },
  { id: "bell-big-blue", name: "Big Blue", cup: "Bell", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/bell/big-blue.webp", game: "mk8dx" },
  { id: "golden-dash-paris-promenade", name: "Paris Promenade", cup: "Golden Dash", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/golden-dash/paris-promenade.webp", game: "mk8dx" },
  { id: "golden-dash-toad-circuit", name: "Toad Circuit", cup: "Golden Dash", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/golden-dash/toad-circuit.webp", game: "mk8dx" },
  { id: "golden-dash-choco-mountain", name: "Choco Mountain", cup: "Golden Dash", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/golden-dash/choco-mountain.webp", game: "mk8dx" },
  { id: "golden-dash-coconut-mall", name: "Coconut Mall", cup: "Golden Dash", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/golden-dash/coconut-mall.webp", game: "mk8dx" },
  { id: "lucky-cat-tokyo-blur", name: "Tokyo Blur", cup: "Lucky Cat", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lucky-cat/tokyo-blur.webp", game: "mk8dx" },
  { id: "lucky-cat-shroom-ridge", name: "Shroom Ridge", cup: "Lucky Cat", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lucky-cat/shroom-ridge.webp", game: "mk8dx" },
  { id: "lucky-cat-sky-garden", name: "Sky Garden", cup: "Lucky Cat", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lucky-cat/sky-garden.webp", game: "mk8dx" },
  { id: "lucky-cat-ninja-hideaway", name: "Ninja Hideaway", cup: "Lucky Cat", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/lucky-cat/ninja-hideaway.webp", game: "mk8dx" },
  { id: "turnip-new-york-minute", name: "New York Minute", cup: "Turnip", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/turnip/new-york-minute.webp", game: "mk8dx" },
  { id: "turnip-mario-circuit-3", name: "Mario Circuit 3", cup: "Turnip", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/turnip/mario-circuit-3.webp", game: "mk8dx" },
  { id: "turnip-kalimari-desert", name: "Kalimari Desert", cup: "Turnip", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/turnip/kalimari-desert.webp", game: "mk8dx" },
  { id: "turnip-waluigi-pinball", name: "Waluigi Pinball", cup: "Turnip", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/turnip/waluigi-pinball.webp", game: "mk8dx" },
  { id: "propeller-sydney-sprint", name: "Sydney Sprint", cup: "Propeller", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/propeller/sydney-sprint.webp", game: "mk8dx" },
  { id: "propeller-snow-land", name: "Snow Land", cup: "Propeller", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/propeller/snow-land.webp", game: "mk8dx" },
  { id: "propeller-mushroom-gorge", name: "Mushroom Gorge", cup: "Propeller", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/propeller/mushroom-gorge.webp", game: "mk8dx" },
  { id: "propeller-sky-high-sundae", name: "Sky-High Sundae", cup: "Propeller", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/propeller/sky-high-sundae.webp", game: "mk8dx" },
  { id: "rock-london-loop", name: "London Loop", cup: "Rock", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/rock/london-loop.webp", game: "mk8dx" },
  { id: "rock-boo-lake", name: "Boo Lake", cup: "Rock", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/rock/boo-lake.webp", game: "mk8dx" },
  { id: "rock-rock-rock-mountain", name: "Rock Rock Mountain", cup: "Rock", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/rock/rock-rock-mountain.webp", game: "mk8dx" },
  { id: "rock-maple-treeway", name: "Maple Treeway", cup: "Rock", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/rock/maple-treeway.webp", game: "mk8dx" },
  { id: "moon-berlin-byways", name: "Berlin Byways", cup: "Moon", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/moon/berlin-byways.webp", game: "mk8dx" },
  { id: "moon-peach-gardens", name: "Peach Gardens", cup: "Moon", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/moon/peach-gardens.webp", game: "mk8dx" },
  { id: "moon-merry-mountain", name: "Merry Mountain", cup: "Moon", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/moon/merry-mountain.webp", game: "mk8dx" },
  { id: "moon-rainbow-road", name: "Rainbow Road", cup: "Moon", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/moon/rainbow-road.webp", game: "mk8dx" },
  { id: "fruit-amsterdam-drift", name: "Amsterdam Drift", cup: "Fruit", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/fruit/amsterdam-drift.webp", game: "mk8dx" },
  { id: "fruit-riverside-park", name: "Riverside Park", cup: "Fruit", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/fruit/riverside-park.webp", game: "mk8dx" },
  { id: "fruit-dk-summit", name: "DK Summit", cup: "Fruit", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/fruit/dk-summit.webp", game: "mk8dx" },
  { id: "fruit-yoshis-island", name: "Yoshi's Island", cup: "Fruit", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/fruit/yoshi-island.webp", game: "mk8dx" },
  { id: "boomerang-bangkok-rush", name: "Bangkok Rush", cup: "Boomerang", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/boomerang/bangkok-rush.webp", game: "mk8dx" },
  { id: "boomerang-mario-circuit", name: "Mario Circuit", cup: "Boomerang", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/boomerang/mario-circuit.webp", game: "mk8dx" },
  { id: "boomerang-waluigi-stadium", name: "Waluigi Stadium", cup: "Boomerang", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/boomerang/waluigi-stadium.webp", game: "mk8dx" },
  { id: "boomerang-singapore-speedway", name: "Singapore Speedway", cup: "Boomerang", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/boomerang/singapore-speedway.webp", game: "mk8dx" },
  { id: "feather-athens-dash", name: "Athens Dash", cup: "Feather", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/feather/athens-dash.webp", game: "mk8dx" },
  { id: "feather-daisy-cruiser", name: "Daisy Cruiser", cup: "Feather", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/feather/daisy-cruiser.webp", game: "mk8dx" },
  { id: "feather-moonview-highway", name: "Moonview Highway", cup: "Feather", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/feather/moonview-highway.webp", game: "mk8dx" },
  { id: "feather-squeaky-clean-sprint", name: "Squeaky Clean Sprint", cup: "Feather", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/feather/squeaky-clean-sprint.webp", game: "mk8dx" },
  { id: "cherry-los-angeles-laps", name: "Los Angeles Laps", cup: "Cherry", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/cherry/los-angeles-laps.webp", game: "mk8dx" },
  { id: "cherry-sunset-wilds", name: "Sunset Wilds", cup: "Cherry", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/cherry/sunset-wilds.webp", game: "mk8dx" },
  { id: "cherry-koopa-cape", name: "Koopa Cape", cup: "Cherry", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/cherry/koopa-cape.webp", game: "mk8dx" },
  { id: "cherry-vancouver-velocity", name: "Vancouver Velocity", cup: "Cherry", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/cherry/vancouver-velocity.webp", game: "mk8dx" },
  { id: "acorn-rome-avanti", name: "Rome Avanti", cup: "Acorn", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/acorn/rome-avanti.webp", game: "mk8dx" },
  { id: "acorn-dk-mountain", name: "DK Mountain", cup: "Acorn", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/acorn/dk-mountain.webp", game: "mk8dx" },
  { id: "acorn-daisy-circuit", name: "Daisy Circuit", cup: "Acorn", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/acorn/daisy-circuit.webp", game: "mk8dx" },
  { id: "acorn-piranha-plant-cove", name: "Piranha Plant Cove", cup: "Acorn", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/acorn/piranha-plant-cove.webp", game: "mk8dx" },
  { id: "spiny-madrid-drive", name: "Madrid Drive", cup: "Spiny", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/spiny/madrid-drive.webp", game: "mk8dx" },
  { id: "spiny-rosalinas-ice-world", name: "Rosalina's Ice World", cup: "Spiny", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/spiny/rosalina-ice-world.webp", game: "mk8dx" },
  { id: "spiny-bowser-castle-3", name: "Bowser Castle 3", cup: "Spiny", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/spiny/bowser-castle-3.webp", game: "mk8dx" },
  { id: "spiny-rainbow-road", name: "Rainbow Road", cup: "Spiny", image: "https://cdn.empac.co/gameshuffle/images/mk8dx/courses/spiny/rainbow-road.webp", game: "mk8dx" },
];
