/**
 * Wheel themes — shared by the free `/wheel-spinner` tool and (later) the
 * Pro overlay so a streamer's chosen theme carries over.
 *
 * A theme is just a serializable bundle of colors: the slice `palette`
 * (cycled across segments) plus accent colors for the bezel, rim, hub,
 * pointer, and labels. Persist/transport the `id`; resolve with `getTheme`.
 */

import { contrastRatio } from "@/lib/theme/contrast";

export interface WheelTheme {
  id: string;
  name: string;
  /** Slice fills, cycled across segments. */
  palette: string[];
  /** Thick outer ring. */
  bezel: string;
  /** Thin inner accent ring + slice separators. */
  rim: string;
  /** Center hub fill + ring. */
  hub: string;
  hubRing: string;
  /** Pointer fill + outline. */
  pointer: string;
  pointerStroke: string;
  /** Label text fill + outline. */
  label: string;
  labelStroke: string;
  /** Glossy radial-sheen opacity (0–1). */
  sheen: number;
}

export const WHEEL_THEMES: WheelTheme[] = [
  {
    id: "classic",
    name: "Classic",
    palette: ["#0e75c1", "#1098ad", "#7048e8", "#e8590c", "#2f9e44", "#c2255c", "#1c7ed6", "#f08c00"],
    bezel: "#0b3a5c",
    rim: "rgba(255,255,255,0.55)",
    hub: "#0f1621",
    hubRing: "rgba(255,255,255,0.7)",
    pointer: "#ffd43b",
    pointerStroke: "rgba(0,0,0,0.45)",
    label: "#ffffff",
    labelStroke: "rgba(0,0,0,0.4)",
    sheen: 0.12,
  },
  {
    id: "midnight",
    name: "Midnight",
    palette: ["#2b3a67", "#3a5a8c", "#1f6f8b", "#4a3f7a", "#2c4a6e", "#155263", "#3d3a72", "#1b3b5a"],
    bezel: "#c6a24e",
    rim: "rgba(214,178,90,0.6)",
    hub: "#0c1830",
    hubRing: "#c6a24e",
    pointer: "#ffd86b",
    pointerStroke: "rgba(0,0,0,0.5)",
    label: "#f3ead2",
    labelStroke: "rgba(0,0,0,0.5)",
    sheen: 0.14,
  },
  {
    id: "neon",
    name: "Neon",
    palette: ["#ff2d95", "#00e5ff", "#b4ff39", "#ffd000", "#7a5cff", "#ff5e00", "#19f0c3", "#ff3860"],
    bezel: "#10131a",
    rim: "rgba(255,255,255,0.7)",
    hub: "#0a0c12",
    hubRing: "#ffffff",
    pointer: "#ffffff",
    pointerStroke: "rgba(0,0,0,0.6)",
    label: "#ffffff",
    labelStroke: "rgba(0,0,0,0.55)",
    sheen: 0.16,
  },
  {
    id: "sunset",
    name: "Sunset",
    palette: ["#ff6b6b", "#ff9f43", "#feca57", "#ff7eb3", "#c44569", "#e66767", "#f8a5c2", "#f78fb3"],
    bezel: "#7a2f5a",
    rim: "rgba(255,255,255,0.6)",
    hub: "#3a1230",
    hubRing: "rgba(255,255,255,0.75)",
    pointer: "#fff3b0",
    pointerStroke: "rgba(0,0,0,0.4)",
    label: "#ffffff",
    labelStroke: "rgba(0,0,0,0.4)",
    sheen: 0.13,
  },
  {
    id: "forest",
    name: "Forest",
    palette: ["#2f9e44", "#157a52", "#74b816", "#5c940d", "#0c8599", "#1098ad", "#2b8a3e", "#099268"],
    bezel: "#1b4332",
    rim: "rgba(255,255,255,0.55)",
    hub: "#0f2a1e",
    hubRing: "rgba(255,255,255,0.7)",
    pointer: "#ffd43b",
    pointerStroke: "rgba(0,0,0,0.4)",
    label: "#ffffff",
    labelStroke: "rgba(0,0,0,0.4)",
    sheen: 0.12,
  },
  {
    id: "candy",
    name: "Candy",
    palette: ["#ff8fab", "#a0e7e5", "#b4a7f5", "#ffd6a5", "#9bf6ff", "#ffadad", "#caffbf", "#fdffb6"],
    bezel: "#ff8fab",
    rim: "rgba(255,255,255,0.85)",
    hub: "#5a3e6b",
    hubRing: "#ffffff",
    pointer: "#ff4d8d",
    pointerStroke: "rgba(255,255,255,0.7)",
    label: "#43314f",
    labelStroke: "rgba(255,255,255,0.6)",
    sheen: 0.18,
  },
];

export const DEFAULT_THEME_ID = "classic";

const BY_ID = new Map(WHEEL_THEMES.map((t) => [t.id, t]));

export function getTheme(id: string | null | undefined): WheelTheme {
  return (id && BY_ID.get(id)) || WHEEL_THEMES[0];
}

/** How slice fills are drawn — orthogonal to the color theme. */
export type FillStyle = "solid" | "gradient" | "stripes" | "dots";

export const FILL_STYLES: { id: FillStyle; name: string }[] = [
  { id: "solid", name: "Solid" },
  { id: "gradient", name: "Gradient" },
  { id: "stripes", name: "Stripes" },
  { id: "dots", name: "Dots" },
];

export const DEFAULT_FILL_STYLE: FillStyle = "solid";

export function getFillStyle(id: string | null | undefined): FillStyle {
  return FILL_STYLES.some((f) => f.id === id) ? (id as FillStyle) : "solid";
}

/**
 * A wheel built from the owner's brand theme, so a streamer's wheel matches the
 * rest of their channel instead of picking a preset that happens to be close.
 *
 * A brand theme is only two colors, but a wheel needs eight distinct slices, so
 * the palette is generated by walking the hue between `primary` and `accent`.
 * Blending in RGB would sag through grey at the midpoint, so this rotates hue in
 * HSL and keeps saturation/lightness in a band that stays readable — the label
 * color is then measured against the darkest slice rather than assumed white.
 */
export const USER_THEME_ID = "user";


function hexToHsl(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(full.slice(i, i + 2), 16) / 255);
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min;
  const l = (max + min) / 2;
  if (d === 0) return [0, 0, l];
  const s = d / (1 - Math.abs(2 * l - 1));
  const hue = max === r ? ((g - b) / d + (g < b ? 6 : 0)) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return [hue * 60, s, l];
}

function hslToHex(hDeg: number, s: number, l: number): string {
  const h = ((hDeg % 360) + 360) % 360;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const seg = Math.floor(h / 60) % 6;
  const [r, g, b] = [[c, x, 0], [x, c, 0], [0, c, x], [0, x, c], [x, 0, c], [c, 0, x]][seg];
  return "#" + [r, g, b].map((v) => Math.round((v + m) * 255).toString(16).padStart(2, "0")).join("");
}

/** Build a full wheel theme from a brand's two colors. */
export function themeFromBrand(primary: string, accent: string, name = "Your theme"): WheelTheme {
  const [h1, s1, l1] = hexToHsl(primary);
  const [h2, s2, l2] = hexToHsl(accent);
  // Shortest way round the colour wheel, so primary→accent never detours
  // through the opposite side of the spectrum.
  let span = h2 - h1;
  if (span > 180) span -= 360;
  if (span < -180) span += 360;

  const COUNT = 8;
  // A fixed lightness band is not enough: a saturated cyan or pink at the same
  // lightness as a blue is far brighter, and white labels measured 1.69:1 on
  // the neon brand. So each slice is darkened until white clears LABEL_MIN.
  // Labels on a wheel are large and bold, which is WCAG's 3:1 case; 3.5 leaves
  // margin for the sheen overlay drawn on top.
  const LABEL_MIN = 3.5;
  // An achromatic colour has no meaningful hue — hexToHsl reports 0, which is
  // red. Applying the saturation floor to it turns a greyscale or black/white
  // brand into a red wheel, so a brand that starts grey stays grey.
  const achromatic = s1 < 0.06 && s2 < 0.06;
  const palette = Array.from({ length: COUNT }, (_, i) => {
    const t = i / (COUNT - 1);
    const blended = s1 + (s2 - s1) * t;
    const sat = achromatic ? blended : Math.min(0.9, Math.max(0.38, blended));
    const hue = h1 + span * t;
    let l = Math.min(0.56, Math.max(0.3, l1 + (l2 - l1) * t));
    let hex = hslToHex(hue, sat, l);
    while (contrastRatio("#ffffff", hex) < LABEL_MIN && l > 0.12) {
      l -= 0.02;
      hex = hslToHex(hue, sat, l);
    }
    return hex;
  });

  const [, , darkest] = hexToHsl(palette.reduce((a, b) => (hexToHsl(a)[2] <= hexToHsl(b)[2] ? a : b)));
  return {
    id: USER_THEME_ID,
    name,
    palette,
    bezel: hslToHex(h1, Math.min(0.8, s1), Math.max(0.16, l1 * 0.42)),
    rim: "rgba(255,255,255,0.55)",
    hub: hslToHex(h1, Math.min(0.5, s1), 0.12),
    hubRing: "rgba(255,255,255,0.7)",
    pointer: hslToHex(h2, Math.min(0.95, s2 + 0.1), 0.62),
    pointerStroke: "rgba(0,0,0,0.45)",
    // Slices are held in the 0.30–0.56 lightness band above, so white labels
    // clear contrast; this only flips if a brand somehow lands lighter.
    label: darkest > 0.62 ? "#10131a" : "#ffffff",
    labelStroke: darkest > 0.62 ? "rgba(255,255,255,0.35)" : "rgba(0,0,0,0.4)",
    sheen: 0.12,
  };
}
