"use client";

import { useState } from "react";
import { Button, Checkbox, Input, Radio, RadioGroup, Select } from "@empac/cascadeds";
import { TournamentRounds } from "@/components/tournament/TournamentRounds";
import { RANDOMIZER_GAMES, RANDOMIZER_GAME_OPTIONS, randomizerGameMeta } from "@/data/randomizer-games";
import {
  generateRounds,
  generateRoundDirective,
  type TournamentRandomizerConfig,
  type GeneratedRound,
  type RandomizerCadence,
} from "@/lib/tournaments/randomizer";

/**
 * DB-free demo of tournament randomized rounds — anyone can try the exact engine
 * the real tournaments use (no restrictions applied in the sandbox). Marketing +
 * a feel-it-before-you-run-it surface. Local state only.
 */

const INITIAL: TournamentRandomizerConfig = {
  enabled: true,
  dimensions: { tracks: { count: 4, noDups: true, tourOnly: false }, combo: true },
  cadence: "reveal_live",
  rounds: 4,
};

export function RandomizerSandbox() {
  const [slug, setSlug] = useState(RANDOMIZER_GAMES[0].slug);
  const [config, setConfig] = useState<TournamentRandomizerConfig>(INITIAL);
  const [rounds, setRounds] = useState<GeneratedRound[]>([]);

  const meta = randomizerGameMeta(slug);
  const d = config.dimensions;
  const setDim = (patch: Partial<TournamentRandomizerConfig["dimensions"]>) =>
    setConfig((c) => ({ ...c, dimensions: { ...c.dimensions, ...patch } }));

  const generateAll = () => setRounds(generateRounds(slug, config, {}));
  const revealNext = () => {
    setRounds((prev) => {
      const next = prev.find((r) => !r.revealed);
      if (next) return prev.map((r) => (r === next ? { ...r, revealed: true } : r));
      if (prev.length < config.rounds) return [...prev, { n: prev.length + 1, revealed: true, directive: generateRoundDirective(slug, config.dimensions, {}, config.cadence === "per_race") }];
      return prev;
    });
  };
  const reset = () => setRounds([]);

  const hasDimension = !!(d.tracks || d.combo || d.items);

  return (
    <div className="comp-card" style={{ marginBottom: "2rem" }}>
      <div style={{ display: "flex", alignItems: "center", gap: "0.6rem", flexWrap: "wrap", marginBottom: "0.5rem" }}>
        <h2 style={{ fontSize: "var(--font-size-12)", margin: 0 }}>Randomized rounds</h2>
        <span className="lounge-mode-badge">GS exclusive</span>
      </div>
      <p style={{ fontSize: "var(--font-size-14)", color: "var(--text-secondary)", marginBottom: "1.25rem", maxWidth: 640 }}>
        Everyone runs the same randomized tracks, combo, and/or items each round — generated by GameShuffle&rsquo;s own
        randomizers and (in a real tournament) held to your build rules. Try it below.
      </p>

      <div style={{ display: "flex", gap: "2rem", flexWrap: "wrap", alignItems: "flex-start", marginBottom: "1.25rem" }}>
        <label style={{ display: "flex", flexDirection: "column", gap: "0.4rem", fontSize: "var(--font-size-12)" }}>
          <span className="account-card__label">Game</span>
          <span style={{ minWidth: "13rem" }}>
            <Select value={slug} onChange={(v) => { setSlug(typeof v === "string" ? v : v[0] ?? slug); setRounds([]); }} options={RANDOMIZER_GAME_OPTIONS} fullWidth />
          </span>
        </label>
        <div>
          <div className="account-card__label" style={{ marginBottom: "0.5rem" }}>What to randomize</div>
          <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
            {(!meta || meta.tracks) && (
            <div style={{ display: "flex", gap: "1rem", alignItems: "center", flexWrap: "wrap" }}>
              <Checkbox checked={!!d.tracks} onChange={(e) => setDim({ tracks: e.target.checked ? { count: 4, noDups: true, tourOnly: false } : undefined })} label="Tracks" />
              {d.tracks && (
                <span style={{ width: "4rem", display: "inline-block" }}>
                  <Input type="number" min={1} max={32} value={d.tracks.count} onChange={(e) => setDim({ tracks: { ...d.tracks!, count: Math.max(1, Math.min(32, Number(e.target.value) || 1)) } })} />
                </span>
              )}
              {d.tracks && meta?.tourOnly && (
                <Checkbox checked={d.tracks.tourOnly} onChange={(e) => setDim({ tracks: { ...d.tracks!, tourOnly: e.target.checked } })} label="Tour only" />
              )}
            </div>
            )}
            {(!meta || meta.combo) && <Checkbox checked={!!d.combo} onChange={(e) => setDim({ combo: e.target.checked ? true : undefined })} label="Shared combo" />}
            {(!meta || meta.items) && (
            <div style={{ display: "flex", gap: "1rem", alignItems: "center", flexWrap: "wrap" }}>
              <Checkbox checked={!!d.items} onChange={(e) => setDim({ items: e.target.checked ? { count: 5 } : undefined })} label="Items" />
              {d.items && (
                <span style={{ width: "4rem", display: "inline-block" }}>
                  <Input type="number" min={1} max={40} value={d.items.count} onChange={(e) => setDim({ items: { count: Math.max(1, Math.min(40, Number(e.target.value) || 1)) } })} />
                </span>
              )}
            </div>
            )}
          </div>
        </div>
        <div>
          <div className="account-card__label" style={{ marginBottom: "0.5rem" }}>Cadence</div>
          <RadioGroup name="sandbox-cadence" value={config.cadence} onChange={(v) => { setConfig((c) => ({ ...c, cadence: v as RandomizerCadence })); setRounds([]); }}>
            <Radio value="reveal_live" label="Reveal live" />
            <Radio value="pre_all" label="Generate all" />
            <Radio value="per_race" label="Per-race combos" />
          </RadioGroup>
        </div>
        <label style={{ display: "flex", flexDirection: "column", gap: "0.4rem", fontSize: "var(--font-size-12)" }}>
          <span className="account-card__label">Rounds</span>
          <span style={{ width: "5rem" }}>
            <Input type="number" min={1} max={16} value={config.rounds} onChange={(e) => setConfig((c) => ({ ...c, rounds: Math.max(1, Math.min(16, Number(e.target.value) || 1)) }))} />
          </span>
        </label>
      </div>

      <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap", marginBottom: rounds.length ? "1.5rem" : 0 }}>
        {config.cadence === "pre_all"
          ? <Button variant="primary" size="small" onClick={generateAll} disabled={!hasDimension}>Generate all rounds</Button>
          : <Button variant="primary" size="small" onClick={revealNext} disabled={!hasDimension}>Reveal next round</Button>}
        {rounds.length > 0 && <Button variant="ghost" size="small" onClick={reset}>Reset</Button>}
      </div>

      {/* pre_all reveals all at once for the demo */}
      <TournamentRounds
        rounds={config.cadence === "pre_all" ? rounds.map((r) => ({ ...r, revealed: true })) : rounds}
        title="Generated rounds"
      />
    </div>
  );
}
