/**
 * Pulls official box art for every game in the catalog (src/data/game-catalog.ts)
 * from Twitch: Helix Get Games by category name (`twitch` or `name`), then the
 * cover from Twitch's CDN, saved as public/images/box-art/<slug>.webp (300 x
 * 400). Writes src/data/box-art.generated.ts (slug → Twitch category id and
 * name), which is what `boxArt()` checks. Skips games that already have a file
 * unless --force; --only <slug> for one game.
 *
 *   DOTENV_CONFIG_PATH=.env.local npx tsx scripts/pull-box-art.ts [--force] [--only slug]
 *
 * Needs TWITCH_CLIENT_ID and TWITCH_CLIENT_SECRET (an app token, no user).
 * A game Twitch can't find by name is listed at the end: fix its `twitch`
 * name in the catalog and run again.
 */

import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { GAME_CATALOG } from "../src/data/game-catalog";

const OUT_DIR = path.join(process.cwd(), "public/images/box-art");
const MANIFEST = path.join(process.cwd(), "src/data/box-art.generated.ts");
const force = process.argv.includes("--force");
const onlyAt = process.argv.indexOf("--only");
const only = onlyAt >= 0 ? process.argv[onlyAt + 1] : null;

type Found = { id: string; name: string; box_art_url: string };

function readManifest(): Record<string, { twitchId: string; twitchName: string }> {
  if (!fs.existsSync(MANIFEST)) return {};
  const m = /export const BOX_ART[^=]*=\s*(\{[\s\S]*\});/.exec(fs.readFileSync(MANIFEST, "utf8"));
  return m ? JSON.parse(m[1]) : {};
}

function writeManifest(data: Record<string, { twitchId: string; twitchName: string }>) {
  const sorted = Object.fromEntries(Object.entries(data).sort(([a], [b]) => a.localeCompare(b)));
  fs.writeFileSync(MANIFEST, `/**
 * Generated by scripts/pull-box-art.ts: which catalog games have box art in
 * public/images/box-art/<slug>.webp, and the Twitch category it came from.
 * Don't edit by hand; run the script.
 */

export const BOX_ART: Record<string, { twitchId: string; twitchName: string }> = ${JSON.stringify(sorted, null, 2)};
`);
}

(async () => {
  const id = process.env.TWITCH_CLIENT_ID, secret = process.env.TWITCH_CLIENT_SECRET;
  if (!id || !secret) throw new Error("TWITCH_CLIENT_ID and TWITCH_CLIENT_SECRET are needed");
  const tok = (await (await fetch(`https://id.twitch.tv/oauth2/token?client_id=${id}&client_secret=${secret}&grant_type=client_credentials`, { method: "POST" })).json()) as { access_token: string };
  const helix = async (q: string) => ((await (await fetch(`https://api.twitch.tv/helix/games?${q}`, { headers: { "Client-Id": id, Authorization: `Bearer ${tok.access_token}` } })).json()) as { data: Found[] }).data ?? [];

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const manifest = readManifest();
  const todo = GAME_CATALOG.filter((g) => (!only || g.slug === only) && (force || !fs.existsSync(path.join(OUT_DIR, `${g.slug}.webp`))));
  const missing: string[] = [];
  let made = 0;

  // Helix takes up to 100 names per call.
  for (let i = 0; i < todo.length; i += 100) {
    const batch = todo.slice(i, i + 100);
    const found = await helix(batch.map((g) => `name=${encodeURIComponent(g.twitch ?? g.name)}`).join("&"));
    const byName = new Map(found.map((f) => [f.name.toLowerCase(), f]));
    for (const g of batch) {
      const hit = byName.get((g.twitch ?? g.name).toLowerCase());
      if (!hit) { missing.push(`${g.slug} (looked for "${g.twitch ?? g.name}")`); continue; }
      try {
        const res = await fetch(hit.box_art_url.replace("{width}x{height}", "600x800"));
        if (!res.ok) throw new Error(`box art ${res.status}`);
        await sharp(Buffer.from(await res.arrayBuffer())).resize(300, 400, { fit: "cover" }).webp({ quality: 82 }).toFile(path.join(OUT_DIR, `${g.slug}.webp`));
        manifest[g.slug] = { twitchId: hit.id, twitchName: hit.name };
        made++;
      } catch (e) {
        missing.push(`${g.slug} (${e instanceof Error ? e.message : e})`);
      }
    }
  }
  // Keep the manifest in step with the files on disk.
  for (const slug of Object.keys(manifest)) if (!fs.existsSync(path.join(OUT_DIR, `${slug}.webp`))) delete manifest[slug];
  writeManifest(manifest);
  console.log(`box art: made ${made}, ${Object.keys(manifest).length} games have art, ${missing.length} not found`);
  for (const m of missing) console.log("  missing", m);
})().catch((e) => { console.error(e); process.exit(1); });
