/**
 * Generated by scripts/pull-box-art.ts: which catalog games have box art in
 * public/images/box-art/<slug>.webp, and the Twitch category it came from.
 * Don't edit by hand; run the script.
 */

export const BOX_ART: Record<string, { twitchId: string; twitchName: string }> = {
  "among-us": {
    "twitchId": "510218",
    "twitchName": "Among Us"
  },
  "animal-crossing-new-horizons": {
    "twitchId": "509538",
    "twitchName": "Animal Crossing: New Horizons"
  },
  "apex-legends": {
    "twitchId": "511224",
    "twitchName": "Apex Legends"
  },
  "balatro": {
    "twitchId": "745589378",
    "twitchName": "Balatro"
  },
  "baldurs-gate-3": {
    "twitchId": "512923",
    "twitchName": "Baldur's Gate 3"
  },
  "brawlhalla": {
    "twitchId": "460316",
    "twitchName": "Brawlhalla"
  },
  "call-of-duty": {
    "twitchId": "1672324422",
    "twitchName": "Call of Duty: Black Ops 6"
  },
  "counter-strike-2": {
    "twitchId": "32399",
    "twitchName": "Counter-Strike"
  },
  "crash-team-racing": {
    "twitchId": "2056946408",
    "twitchName": "Crash Team Racing Nitro-Fueled"
  },
  "dead-by-daylight": {
    "twitchId": "491487",
    "twitchName": "Dead by Daylight"
  },
  "donkey-kong-bananza": {
    "twitchId": "1222247252",
    "twitchName": "Donkey Kong Bananza"
  },
  "dragon-ball-sparking-zero": {
    "twitchId": "400407464",
    "twitchName": "DRAGON BALL: Sparking! ZERO"
  },
  "elden-ring": {
    "twitchId": "512953",
    "twitchName": "ELDEN RING"
  },
  "fall-guys": {
    "twitchId": "512980",
    "twitchName": "Fall Guys"
  },
  "fortnite": {
    "twitchId": "33214",
    "twitchName": "Fortnite"
  },
  "gang-beasts": {
    "twitchId": "459527",
    "twitchName": "Gang Beasts"
  },
  "goldeneye-007": {
    "twitchId": "829248383",
    "twitchName": "GoldenEye 007"
  },
  "golf-with-your-friends": {
    "twitchId": "491381",
    "twitchName": "Golf With Your Friends"
  },
  "guilty-gear-strive": {
    "twitchId": "517159",
    "twitchName": "GUILTY GEAR -STRIVE-"
  },
  "hades-ii": {
    "twitchId": "376500771",
    "twitchName": "Hades II"
  },
  "halo-infinite": {
    "twitchId": "506416",
    "twitchName": "Halo Infinite"
  },
  "hollow-knight-silksong": {
    "twitchId": "511391",
    "twitchName": "Hollow Knight: Silksong"
  },
  "it-takes-two": {
    "twitchId": "2070421261",
    "twitchName": "It Takes Two"
  },
  "jackbox": {
    "twitchId": "493174",
    "twitchName": "Jackbox Party Packs"
  },
  "kirby-air-riders": {
    "twitchId": "2086806174",
    "twitchName": "Kirby Air Riders"
  },
  "league-of-legends": {
    "twitchId": "21779",
    "twitchName": "League of Legends"
  },
  "lethal-company": {
    "twitchId": "2085980140",
    "twitchName": "Lethal Company"
  },
  "luigis-mansion-3": {
    "twitchId": "509541",
    "twitchName": "Luigi's Mansion 3"
  },
  "mario-golf-super-rush": {
    "twitchId": "339386743",
    "twitchName": "Mario Golf: Super Rush"
  },
  "mario-kart-64": {
    "twitchId": "9250",
    "twitchName": "Mario Kart 64"
  },
  "mario-kart-8-deluxe": {
    "twitchId": "941530474",
    "twitchName": "Mario Kart 8 Deluxe"
  },
  "mario-kart-double-dash": {
    "twitchId": "17189",
    "twitchName": "Mario Kart: Double Dash!!"
  },
  "mario-kart-wii": {
    "twitchId": "18871",
    "twitchName": "Mario Kart Wii"
  },
  "mario-kart-world": {
    "twitchId": "1826300051",
    "twitchName": "Mario Kart World"
  },
  "mario-party-2": {
    "twitchId": "11176",
    "twitchName": "Mario Party 2"
  },
  "mario-party-3": {
    "twitchId": "11432",
    "twitchName": "Mario Party 3"
  },
  "mario-party-n64": {
    "twitchId": "5887",
    "twitchName": "Mario Party"
  },
  "mario-party-series": {
    "twitchId": "1471610418",
    "twitchName": "Super Mario Party Jamboree"
  },
  "mario-party-superstars": {
    "twitchId": "1068239917",
    "twitchName": "Mario Party Superstars"
  },
  "mario-strikers-battle-league": {
    "twitchId": "1769394593",
    "twitchName": "Mario Strikers: Battle League"
  },
  "mario-tennis-aces": {
    "twitchId": "502429",
    "twitchName": "Mario Tennis Aces"
  },
  "marvel-rivals": {
    "twitchId": "1264310518",
    "twitchName": "Marvel Rivals"
  },
  "metroid-prime-4": {
    "twitchId": "497454",
    "twitchName": "Metroid Prime 4: Beyond"
  },
  "minecraft": {
    "twitchId": "27471",
    "twitchName": "Minecraft"
  },
  "mortal-kombat-1": {
    "twitchId": "904864974",
    "twitchName": "Mortal Kombat 1"
  },
  "nintendo-switch-sports": {
    "twitchId": "2044170173",
    "twitchName": "Nintendo Switch Sports"
  },
  "overcooked-2": {
    "twitchId": "506458",
    "twitchName": "Overcooked! 2"
  },
  "overwatch": {
    "twitchId": "515025",
    "twitchName": "Overwatch"
  },
  "party-animals": {
    "twitchId": "518186",
    "twitchName": "Party Animals"
  },
  "peak": {
    "twitchId": "1081998272",
    "twitchName": "PEAK"
  },
  "perfect-dark": {
    "twitchId": "2686",
    "twitchName": "PERFECT DARK"
  },
  "phasmophobia": {
    "twitchId": "518184",
    "twitchName": "Phasmophobia"
  },
  "pico-park": {
    "twitchId": "513056",
    "twitchName": "PICO PARK"
  },
  "pikmin-4": {
    "twitchId": "494998",
    "twitchName": "Pikmin 4"
  },
  "pokemon-champions": {
    "twitchId": "1931693784",
    "twitchName": "Pokémon Champions"
  },
  "pokemon-firered-leafgreen": {
    "twitchId": "13332",
    "twitchName": "Pokémon FireRed/LeafGreen"
  },
  "pokemon-legends-z-a": {
    "twitchId": "997367275",
    "twitchName": "Pokémon Legends: Z-A"
  },
  "pokemon-scarlet-violet": {
    "twitchId": "670867987",
    "twitchName": "Pokémon Scarlet/Violet"
  },
  "pokemon-stadium": {
    "twitchId": "6657",
    "twitchName": "Pokémon Stadium"
  },
  "pokemon-stadium-2": {
    "twitchId": "5620",
    "twitchName": "Pokémon Stadium 2"
  },
  "pokemon-tcg": {
    "twitchId": "9618",
    "twitchName": "Pokémon Trading Card Game"
  },
  "pokemon-unite": {
    "twitchId": "518379",
    "twitchName": "Pokémon UNITE"
  },
  "rainbow-six-siege": {
    "twitchId": "460630",
    "twitchName": "Rainbow Six Siege"
  },
  "repo": {
    "twitchId": "1294658629",
    "twitchName": "R.E.P.O."
  },
  "rivals-of-aether-ii": {
    "twitchId": "330654616",
    "twitchName": "Rivals of Aether II"
  },
  "rocket-league": {
    "twitchId": "30921",
    "twitchName": "Rocket League"
  },
  "sonic-racing-crossworlds": {
    "twitchId": "1135492840",
    "twitchName": "Sonic Racing: CrossWorlds"
  },
  "splatoon-3": {
    "twitchId": "1158884259",
    "twitchName": "Splatoon 3"
  },
  "split-fiction": {
    "twitchId": "1354355809",
    "twitchName": "Split Fiction"
  },
  "stardew-valley": {
    "twitchId": "490744",
    "twitchName": "Stardew Valley"
  },
  "street-fighter-6": {
    "twitchId": "55453844",
    "twitchName": "Street Fighter 6"
  },
  "super-mario-bros-wonder": {
    "twitchId": "463447553",
    "twitchName": "Super Mario Bros. Wonder"
  },
  "super-mario-odyssey": {
    "twitchId": "493997",
    "twitchName": "Super Mario Odyssey"
  },
  "super-mario-party": {
    "twitchId": "506454",
    "twitchName": "Super Mario Party"
  },
  "super-mario-party-jamboree": {
    "twitchId": "1471610418",
    "twitchName": "Super Mario Party Jamboree"
  },
  "super-smash-bros-melee": {
    "twitchId": "16282",
    "twitchName": "Super Smash Bros. Melee"
  },
  "super-smash-bros-ultimate": {
    "twitchId": "504461",
    "twitchName": "Super Smash Bros. Ultimate"
  },
  "tekken-8": {
    "twitchId": "538054672",
    "twitchName": "TEKKEN 8"
  },
  "tetris-99": {
    "twitchId": "511396",
    "twitchName": "TETRIS 99"
  },
  "valorant": {
    "twitchId": "516575",
    "twitchName": "VALORANT"
  },
  "warioware-move-it": {
    "twitchId": "1015973760",
    "twitchName": "WarioWare: Move It!"
  },
  "zelda-breath-of-the-wild": {
    "twitchId": "110758",
    "twitchName": "The Legend of Zelda: Breath of the Wild"
  },
  "zelda-tears-of-the-kingdom": {
    "twitchId": "512998",
    "twitchName": "The Legend of Zelda: Tears of the Kingdom"
  }
};
